---
label: Product
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: layout
  label: layout
- type: number
  name: order
  label: order
- type: field_group
  name: seo
  label: seo
  fields:
  - type: text
    name: title
    label: title
  - type: text
    name: description
    label: description
  - type: field_group_list
    name: extra
    label: extra
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: value
      label: value
    - type: text
      name: keyName
      label: keyName
